[package]
name = "harmi"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embedded-hal = "1.0.0"
hd44780-driver = "0.4.0"
panic-halt = "1.0.0"
rp-pico = "0.9.0"
usb-device = "0.3.2"
usbd-midi = "0.3.0"
